import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[calc(100vh-55px)]`}
      >
        <header className="flex items-center justify-between py-2 px-4 border-b">
          <Image src="/logo.svg" width={150} height={37} alt="Tarteeb Logo" />
          <span className="font-medium text-2xl text-red-500">EXAM</span>
        </header>
        {children}
      </body>
    </html>
  );
}
